version: "3"
volumes: 
  dynamodb_data:
services:
    db:
      image: amazon/dynamodb-local:latest
      command: -jar DynamoDBLocal.jar -sharedDb -dbPath /usr/local/var/dynamodb/data
      volumes:
        - .data:/usr/local/var/dynamodb/data
      ports:
        - "8000:8000"
